version: '3'
services:
    db:
        image: mysql:5.7.32
        restart: unless-stopped
        volumes:
            - test-task_mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3306:3306"
volumes:
    test-task_mysql: